
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pavan
 */
public class Registeration extends javax.swing.JApplet {

    /**
     * Initializes the applet Registeration
     */
    String s11;
    String ph_num;
    String suserdata=new String();
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registeration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login_usrname = new javax.swing.JTextField();
        login_pwd = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fnamr_reg = new javax.swing.JTextField();
        lname_reg = new javax.swing.JTextField();
        usrname_reg = new javax.swing.JTextField();
        pwd_reg = new javax.swing.JPasswordField();
        conpwd_reg = new javax.swing.JPasswordField();
        mail_reg = new javax.swing.JTextField();
        phno_reg = new javax.swing.JTextField();
        reg_btn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1043, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 587, 1043, 0);
        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(810, -40, 5, 5);

        jPanel2.setLayout(null);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon("E:\\CloudSecurity_phts\\cool-loading-animated-gif-8.gif")); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(252, 0, 408, 342);

        jLabel12.setIcon(new javax.swing.ImageIcon("E:\\CloudSecurity_phts\\black123.jpg")); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 0, 990, 340);

        jTabbedPane2.addTab("HOME", jPanel2);

        jPanel5.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Charlemagne Std", 1, 14)); // NOI18N
        jLabel1.setText("USERNAME");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(275, 97, 100, 23);

        jLabel2.setFont(new java.awt.Font("Charlemagne Std", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(275, 149, 100, 15);

        login_usrname.setName(""); // NOI18N
        login_usrname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_usrnameActionPerformed(evt);
            }
        });
        jPanel5.add(login_usrname);
        login_usrname.setBounds(401, 98, 205, 30);
        jPanel5.add(login_pwd);
        login_pwd.setBounds(401, 146, 205, 30);

        login_btn.setText("SUBMIT");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        jPanel5.add(login_btn);
        login_btn.setBounds(358, 208, 69, 23);

        jButton2.setText("CANCEL");
        jPanel5.add(jButton2);
        jButton2.setBounds(535, 208, 71, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon("E:\\CloudSecurity_phts\\java_cod1.JPG")); // NOI18N
        jPanel5.add(jLabel10);
        jLabel10.setBounds(0, 0, 970, 340);

        jTabbedPane2.addTab("LOGIN", jPanel5);

        jPanel4.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Pericles Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FIRST NAME");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(194, 36, 216, 25);

        jLabel4.setFont(new java.awt.Font("Pericles Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LAST NAME");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(194, 67, 140, 24);

        jLabel5.setFont(new java.awt.Font("Pericles Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("USERNAME");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(194, 97, 216, 23);

        jLabel6.setFont(new java.awt.Font("Pericles Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PASSWORD");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(194, 126, 216, 26);

        jLabel7.setFont(new java.awt.Font("Pericles Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RE-ENTER PASSWORD");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(194, 158, 220, 22);

        jLabel8.setFont(new java.awt.Font("Pericles Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("E-MAIL");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(194, 186, 216, 24);

        jLabel9.setFont(new java.awt.Font("Pericles Light", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PHONE NUMBER");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(194, 216, 216, 26);
        jPanel4.add(fnamr_reg);
        fnamr_reg.setBounds(414, 38, 392, 20);
        jPanel4.add(lname_reg);
        lname_reg.setBounds(414, 69, 392, 20);

        usrname_reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrname_regActionPerformed(evt);
            }
        });
        jPanel4.add(usrname_reg);
        usrname_reg.setBounds(414, 100, 392, 20);
        jPanel4.add(pwd_reg);
        pwd_reg.setBounds(414, 129, 392, 20);

        conpwd_reg.setText("jPasswordField3");
        jPanel4.add(conpwd_reg);
        conpwd_reg.setBounds(414, 159, 392, 20);
        jPanel4.add(mail_reg);
        mail_reg.setBounds(414, 188, 392, 20);
        jPanel4.add(phno_reg);
        phno_reg.setBounds(414, 219, 392, 20);

        reg_btn.setText("REGISTER");
        reg_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_btnActionPerformed(evt);
            }
        });
        jPanel4.add(reg_btn);
        reg_btn.setBounds(377, 260, 81, 23);

        jButton4.setText("REVERT ");
        jPanel4.add(jButton4);
        jButton4.setBounds(549, 260, 73, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\CloudSecurity_phts\\javacode_2.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(0, 0, 940, 340);

        jTabbedPane2.addTab("REGISTERATION", jPanel4);

        getContentPane().add(jTabbedPane2);
        jTabbedPane2.setBounds(40, 50, 900, 370);
    }// </editor-fold>//GEN-END:initComponents

    public void reg_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_btnActionPerformed
        // TODO add your handling code here:
        PreparedStatement statement1;
        statement1 = null;
        ResultSet resultSet=null;
        String s1,s2,s3,s6,s7;
        String s="You Have been Registered";
        if(evt.getSource()==reg_btn)
        {
             s1= fnamr_reg.getText();
             s2=lname_reg.getText();
             s3=usrname_reg.getText();
             char s4[]=pwd_reg.getPassword();
             char s5[]=conpwd_reg.getPassword();
             s6=mail_reg.getText();
             s7=phno_reg.getText();
             
              try
         {
             Class.forName("org.apache.derby.jdbc.ClientDriver");
             Connection connection=(Connection)DriverManager.getConnection("jdbc:derby://localhost:1527/photodb","pavan","pa1dperfect");
             statement1=(PreparedStatement) connection.prepareStatement("insert into CS_REGISTER(f_name,l_name,usr_name,pwd_name,con_pwd,mail_name,ph_num)values(?,?,?,?,?,?,?)");
             statement1.setString(1,s1);
             statement1.setString(2,s2);
             statement1.setString(3,s3);
             statement1.setString(4,String.valueOf(s4));
             statement1.setString(5,String.valueOf(s5));
             statement1.setString(6,s6);
             statement1.setString(7,s7);
             statement1.execute();
             
             //resultSet=statement1.executeQuery();
            // boolean exists=false;
             JOptionPane.showMessageDialog(this,s);
             
             
         }
             catch(Exception e){
               JOptionPane.showMessageDialog(this,"USERNAME ^already exists");
              e.printStackTrace();
              
         }
    }//GEN-LAST:event_reg_btnActionPerformed
    }
    public void usrname_regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrname_regActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usrname_regActionPerformed

    public void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
         PreparedStatement statement1;
        statement1 = null;
        ResultSet resultSet=null;
        filesavingtodbms ftsbe=new filesavingtodbms();
        filesavingtodbms2 ftsbe2=new filesavingtodbms2();
        filesavingtodbms3 ftsbe3=new filesavingtodbms3();
        filesavingtodbms4 ftsbe4=new filesavingtodbms4();
        filesavingtodbms5 ftsbe5=new filesavingtodbms5();
        SMS sew=new SMS();
       
        //login_usrname=new javax.swing.JTextField();
        s11= login_usrname.getText();
        /*System.out.println("before");
        System.out.println(s11);
        System.out.println("after");*/
       new filesavingtodbms().fv(s11);
       new filesavingtodbms2().fv(s11);
       new filesavingtodbms3().fv(s11);
       new filesavingtodbms4().fv(s11);
       new filesavingtodbms5().fv(s11);
        try {
            new Acessoldtable().fv1(s11);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Registeration.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(evt.getSource()==login_btn)
        {
             this.s11= this.login_usrname.getText();
             //System.out.println(s11);
             //ftsbe.username=s11;
             char s22[]=login_pwd.getPassword();
            
              try
         {
             Class.forName("org.apache.derby.jdbc.ClientDriver");
             Connection connection=(Connection)DriverManager.getConnection("jdbc:derby://localhost:1527/photodb","pavan","pa1dperfect");
             statement1=(PreparedStatement) connection.prepareStatement("select usr_name,pwd_name,ph_num from CS_REGISTER where usr_name=? and pwd_name=? ");
             statement1.setString(1,s11);
             statement1.setString(2,String.valueOf(s22));
             statement1.execute();
             
             resultSet=statement1.executeQuery();
             System.out.println("1pavan"+resultSet);
             boolean exists=false;
               // ph_num=resultSet.getString(2);
               // System.out.println(ph_num);
        //
            
           if(resultSet.next())//  while(resultSet.next())
             {
                 ph_num=resultSet.getString(3);
                 System.out.println(ph_num);
                 sew.getphnumber(this.ph_num);
                 
                 exists=true;
                 JOptionPane.showMessageDialog(null,"Login","Successful",JOptionPane.INFORMATION_MESSAGE);
                 Loading ld=new Loading();
                 ld.setVisible(true);
                 setVisible(false);
                 
                
             }
           else JOptionPane.showMessageDialog(null,"Login FAILED ","**USER NOT EXISTS**",JOptionPane.INFORMATION_MESSAGE);
             
            
            
         }
               
             catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error");
                e.printStackTrace();
         }
              
        }
        
    }//GEN-LAST:event_login_btnActionPerformed

    public void login_usrnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_usrnameActionPerformed
        // TODO add your handling code here:
        //suserdata=login_usrname.getText();
        //System.out.println(suserdata);
    }//GEN-LAST:event_login_usrnameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPasswordField conpwd_reg;
    private javax.swing.JTextField fnamr_reg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField lname_reg;
    private javax.swing.JButton login_btn;
    private javax.swing.JPasswordField login_pwd;
    private javax.swing.JTextField login_usrname;
    private javax.swing.JTextField mail_reg;
    private javax.swing.JTextField phno_reg;
    private javax.swing.JPasswordField pwd_reg;
    private javax.swing.JButton reg_btn;
    private javax.swing.JTextField usrname_reg;
    // End of variables declaration//GEN-END:variables
}
